project:
  type: website
  resources:
    - sleepdiaries-icon.png
    - scoreme-icon.svg

website:
  title: "Circadia"
  site-url: "https://circadia-lab.uk"
  description: "We are an interdisciplinary team researching the intersection of physics, computer science, and physiology, with a focus on sleep, rhythmicity, and medical signals."
  favicon: "favicon.png"
  twitter-card: true
  image: "logo.png"
  open-graph: # https://quarto.org/docs/websites/website-tools.html#open-graph
    site-name: "Circadia"
    locale: "en_GB"
  page-footer: "Made with ❤️ and Quarto. © 2026. This work is openly licensed via CC BY 4.0"
  navbar:
    logo: "logo.png"
    left:
      - text: Home
        icon: house-fill
        href: index.qmd
      - text: People
        icon: people-fill
        href: people.qmd
      - text: Publications
        icon: newspaper
        href: publications.qmd
      - text: Projects
        icon: folder-fill
        href: projects.qmd
      - text: Tutorials
        icon: file-earmark-richtext
        href: blog.qmd
      - text: Join us/Visit
        icon: person-plus-fill
        href: join.qmd
      - text: Design
        icon: palette-fill
        href: design.qmd
    tools:
      - icon: github
        href: https://github.com/circadia-bio/website
      - icon: rss
        menu:
            - text: Publications
              href: publications.xml
            - text: Posts
              href: blog.xml
      
format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [cosmo, stylesd.scss]
    highlight-style: arrow
    page-layout: full
