project:
  type: website

website:
  title: "Home"
  site-url: "https://circadia.bio"
  twitter-card: true
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto. © 2025. This work is openly licensed via CC BY 4.0"
  navbar:
    left:
      - text: People
        icon: people-fill
        href: people.qmd
      - text: Publications
        icon: newspaper
        href: publications.qmd
      - text: Blog
        icon: file-earmark-richtext
        href: blog.qmd
    tools:
      - icon: github
        href: https://github.com/circadia-bio/website
      - icon: rss
        menu:
            - text: Publications
              href: publications.xml
            - text: Posts
              href: publications.xml
      
format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [cosmo, stylesd.scss]
    page-layout: full
  